/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package OnlineShoppingApp;

import org.springframework.context.support-3.1.0.RELEASE.jar;
import java.util.List;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
    public static void main( String[] args )
    {
    	ApplicationContext context = new ClassPathXmlApplicationContext("springbeans.xml");
    	
    	User U = context.getBean("user",User.class);
    	System.out.println("User-Name       : " + U.getUsername());
    	System.out.println("Email Id        : " + U.getEmail());
    	System.out.println("Password        : " + U.getPassword());
    	System.out.println("Shipping Address: " + U.getShipping_address());
    	System.out.println("Billing Address : " + U.getBilling_address());
    	System.out.println();
    	System.out.println();
    	
    	Product P = context.getBean("product",Product.class);
    	System.out.println("Product Name        : " + P.getProduct_name());
    	System.out.println("Price               : " + P.getPrice());
    	System.out.println("No. of products left: " + P.getQuantity_in_stock());
    	System.out.println("Image Location      : " + P.getImagelocation());
    	System.out.println();
    	System.out.println();
    	
    	Order O = context.getBean("order",Order.class);
    	List<Cart> cart = O.getCartList();
    	for(Cart c:cart) {
    	System.out.println("User            : "+ c.getUser().getUsername());
    	System.out.println("Email Id        : "+ c.getUser().getEmail());
    	System.out.println("Password        : "+ c.getUser().getPassword());
    	System.out.println("Shipping Address: "+ c.getUser().getShipping_address());
    	System.out.println("Billing Address : "+ c.getUser().getBilling_address());
    	System.out.println();
    	System.out.println();
    	
    	List<Product> productList = c.getProductList();
        for(Product p:productList) {
        	 System.out.println(p.getProduct_name());
        	 System.out.println(p.getPrice());
        	 System.out.println(p.getQuantity_in_stock());
        	 System.out.println(p.getImagelocation());
         	System.out.println();
        	System.out.println();
        }
        System.out.println("Total Amount : "+ c.getTotal_amount());
        System.out.println("Status       : "+ c.isStatus());
        System.out.println("Confirm Order: "+ c.isConfirmOrder());    	
    	}
    }
}
